version: '3.8'
services:
  db:
    image: postgres:12.9
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nestjs
    
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - nestjs
    restart: always
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
  app:
    container_name: test
    image: test
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - nestjs
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links: 
      - db
    depends_on: 
      - db
    restart: always



networks:
  nestjs:
    driver: bridge

volumes:
  db_data: