name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.4.0
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Test
      run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy to DigitalOcean
      uses: digitalocean/action-doctl@v1
      with:
        command: 'compute droplet create'
        arguments: '--name test --region nyc3 --image ubuntu-20-04-x64 --size s-1vcpu-1gb --ssh-keys 12:34:56:78:90 --wait'
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.dop_v1_ae03ee6bb14253815931477182d3fafbfca17a7391a884ae8b80a68af8ba67d8 }}
